INSERT INTO agencies (agency_name, category, is_visible) VALUES ('BLM','Federal',True);
INSERT INTO agencies (agency_name, category, is_visible) VALUES ('DEQ','State',True);
INSERT INTO agencies (agency_name, category, is_visible) VALUES ('DFG','State',True);
INSERT INTO agencies (agency_name, category, is_visible) VALUES ('DWR','State',True);
INSERT INTO agencies (agency_name, category, is_visible) VALUES ('EPA','Federal',True);
INSERT INTO agencies (agency_name, category, is_visible) VALUES ('NPS','Federal', True);
INSERT INTO agencies (agency_name, category, is_visible) VALUES ('NRCS','Federal', True);
INSERT INTO agencies (agency_name, category, is_visible) VALUES ('OTHER','Federal', True);
INSERT INTO agencies (agency_name, category, is_visible) VALUES ('OTHER','Private/NGO',True);
INSERT INTO agencies (agency_name, category, is_visible) VALUES ('OTHER','University', True);
INSERT INTO agencies (agency_name, category, is_visible) VALUES ('STATE','State', True);
INSERT INTO agencies (agency_name, category, is_visible) VALUES ('TRIBE','Tribe', True);
INSERT INTO agencies (agency_name, category, is_visible) VALUES ('Unresolved','Federal', True);
INSERT INTO agencies (agency_name, category, is_visible) VALUES ('Unresolved', 'State', True);
INSERT INTO agencies (agency_name, category, is_visible) VALUES ('Unresolved','University', True);
INSERT INTO agencies (agency_name, category, is_visible) VALUES ('USFS','Federal', True);
INSERT INTO agencies (agency_name, category, is_visible) VALUES ('USFWS','Federal', True);
INSERT INTO agencies (agency_name, category, is_visible) VALUES ('USGS','Federal', True);