INSERT INTO countries (country_id, country_name, abbreviation) VALUES (1, 'Aruba', 'ABW');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (2, 'Antigua and Barbuda', 'ATG');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (3, 'Afghanistan', 'AFG');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (4, 'Algeria', 'DZA');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (5, 'Azerbaijan', 'AZE');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (6, 'Albania', 'ALB');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (7, 'Armenia', 'ARM');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (8, 'Andorra', 'AND');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (9, 'Angola', 'AGO');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (10, 'American Samoa', 'ASM');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (11, 'Argentina', 'ARG');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (12, 'Australia', 'AUS');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (13, 'Austria', 'AUT');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (14, 'Anguilla', 'AIA');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (15, 'Bahrain', 'BHR');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (16, 'Barbados', 'BRB');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (17, 'Botswana', 'BWA');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (18, 'Bermuda', 'BMU');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (19, 'Belgium', 'BEL');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (20, 'Bahamas, The', 'BHS');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (21, 'Bangladesh', 'BGD');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (22, 'Belize', 'BLZ');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (23, 'Bosnia and Herzegovina', 'BIH');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (24, 'Bolivia', 'BOL');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (25, 'Myanmar (Burma)', 'MMR');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (26, 'Benin', 'BEN');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (27, 'Byelarus', 'BLR');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (28, 'Solomon Islands', 'SLB');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (29, 'Brazil', 'BRA');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (30, 'Bhutan', 'BTN');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (31, 'Bulgaria', 'BGR');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (32, 'Bouvet Island', 'NOR1');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (33, 'Brunei', 'BRN');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (34, 'Burundi', 'BDI');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (35, 'Canada', 'CAN');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (36, 'Cambodia', 'KHM');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (37, 'Chad', 'TCD');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (38, 'Sri Lanka', 'LKA');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (39, 'Congo', 'COG');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (40, 'Zaire', 'ZAR');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (41, 'China', 'CHN');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (42, 'Chile', 'CHL');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (43, 'Cayman Islands', 'CYM');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (44, 'Cocos (Keeling) Islands', 'CCK');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (45, 'Cameroon', 'CMR');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (46, 'Comoros', 'COM');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (47, 'Colombia', 'COL');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (48, 'Northern Mariana Islands', 'MNP');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (49, 'Costa Rica', 'CRI');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (50, 'Central African Republic', 'CAF');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (51, 'Cuba', 'CUB');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (52, 'Cape Verde', 'CPV');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (53, 'Cook Islands', 'COK');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (54, 'Cyprus', 'CYP');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (55, 'Denmark', 'DNK');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (56, 'Djibouti', 'DJI');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (57, 'Dominica', 'DMA');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (58, 'Jarvis Island', 'UMI1');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (59, 'Dominican Republic', 'DOM');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (60, 'Ecuador', 'ECU');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (61, 'Egypt', 'EGY');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (62, 'Ireland', 'IRL');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (63, 'Equatorial Guinea', 'GNQ');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (64, 'Estonia', 'EST');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (65, 'Eritrea', 'ERI');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (66, 'El Salvador', 'SLV');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (67, 'Ethiopia', 'ETH');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (68, 'Czech Republic', 'CZE');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (69, 'French Guiana', 'GUF');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (70, 'Finland', 'FIN');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (71, 'Falkland Islands (Islas Malvinas)', 'FLK');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (72, 'Federated States of Micronesia', 'FSM');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (73, 'Faroe Islands', 'FRO');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (74, 'French Polynesia', 'PYF');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (75, 'Baker Island', 'UMI2');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (76, 'France', 'FRA');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (77, 'French Southern & Antarctic Lands', 'ATF');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (78, 'Gambia, The', 'GMB');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (79, 'Gabon', 'GAB');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (80, 'Georgia', 'GEO');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (81, 'Ghana', 'GHA');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (82, 'Gibraltar', 'GIB');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (83, 'Grenada', 'GRD');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (84, 'Guernsey', 'XGK');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (85, 'Greenland', 'GRL');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (86, 'Germany', 'DEU');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (87, 'Glorioso Islands', 'REU1');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (88, 'Guadeloupe', 'GLP');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (89, 'Guam', 'GUM');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (90, 'Greece', 'GRC');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (91, 'Guatemala', 'GTM');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (92, 'Guinea', 'GIN');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (93, 'Guyana', 'GUY');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (94, 'Gaza Strip', 'GZ');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (95, 'Haiti', 'HTI');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (96, 'Heard Island & McDonald Islands', 'HMD');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (97, 'Honduras', 'HND');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (98, 'Howland Island', 'UMI3');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (99, 'Croatia', 'HRV');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (100, 'Hungary', 'HUN');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (101, 'Iceland', 'ISL');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (102, 'Indonesia', 'IDN');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (103, 'Man, Isle of', 'XIM');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (104, 'India', 'IND');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (105, 'British Indian Ocean Territory', 'IOT');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (106, 'Iran', 'IRN');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (107, 'Israel', 'ISR');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (108, 'Italy', 'ITA');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (109, 'Ivory Coast', 'CIV');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (110, 'Iraq', 'IRQ');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (111, 'Japan', 'JPN');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (112, 'Jersey', 'XJE');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (113, 'Jamaica', 'JAM');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (114, 'Jan Mayen', 'SJM2');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (115, 'Jordan', 'JOR');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (116, 'Johnston Atoll', 'UMI4');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (117, 'Juan De Nova Island', 'REU2');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (118, 'Kenya', 'KEN');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (119, 'Kyrgyzstan', 'KGZ');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (120, 'North Korea', 'PRK');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (121, 'Kiribati', 'KIR');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (122, 'South Korea', 'KOR');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (123, 'Christmas Island', 'CXR');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (124, 'Kuwait', 'KWT');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (125, 'Kazakhstan', 'KAZ');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (126, 'Laos', 'LAO');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (127, 'Lebanon', 'LBN');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (128, 'Latvia', 'LVA');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (129, 'Lithuania', 'LTU');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (130, 'Liberia', 'LBR');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (131, 'Slovakia', 'SVK');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (132, 'Liechtenstein', 'LIE');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (133, 'Lesotho', 'LSO');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (134, 'Luxembourg', 'LUX');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (135, 'Libya', 'LBY');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (136, 'Madagascar', 'MDG');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (137, 'Martinique', 'MTQ');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (138, 'Macau', 'MAC');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (139, 'Moldova', 'MDA');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (140, 'Mayotte', 'MYT');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (141, 'Mongolia', 'MNG');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (142, 'Montserrat', 'MSR');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (143, 'Malawi', 'MWI');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (144, 'Macedonia', 'MKD');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (145, 'Mali', 'MLI');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (146, 'Monaco', 'MCO');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (147, 'Morocco', 'MAR');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (148, 'Mauritius', 'MUS');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (149, 'Midway Islands', 'UMI5');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (150, 'Mauritania', 'MRT');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (151, 'Malta', 'MLT');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (152, 'Oman', 'OMN');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (153, 'Maldives', 'MDV');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (154, 'Montenegro', 'MON');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (155, 'Mexico', 'MEX');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (156, 'Malaysia', 'MYS');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (157, 'Mozambique', 'MOZ');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (158, 'New Caledonia', 'NCL');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (159, 'Niue', 'NIU');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (160, 'Norfolk Island', 'NFK');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (161, 'Niger', 'NER');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (162, 'Vanuatu', 'VUT');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (163, 'Nigeria', 'NGA');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (164, 'Netherlands', 'NLD');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (165, 'Norway', 'NOR');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (166, 'Nepal', 'NPL');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (167, 'Nauru', 'NRU');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (168, 'Suriname', 'SUR');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (169, 'Netherlands Antilles', 'ANT');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (170, 'Nicaragua', 'NIC');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (171, 'New Zealand', 'NZL');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (172, 'Paraguay', 'PRY');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (173, 'Pitcairn Islands', 'PCN');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (174, 'Peru', 'PER');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (175, 'Paracel Islands', 'XPF');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (176, 'Spratly Islands', 'XPG');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (177, 'Pakistan', 'PAK');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (178, 'Poland', 'POL');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (179, 'Panama', 'PAN');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (180, 'Portugal', 'PRT');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (181, 'Papua New Guinea', 'PNG');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (182, 'Pacific Islands (Palau)', 'PLW');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (183, 'Guinea-Bissau', 'GNB');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (184, 'Qatar', 'QAT');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (185, 'Reunion', 'REU');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (186, 'Marshall Islands', 'MHL');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (187, 'Romania', 'ROM');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (188, 'Philippines', 'PHL');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (189, 'Puerto Rico', 'PRI');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (190, 'Russia', 'RUS');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (191, 'Rwanda', 'RWA');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (192, 'Saudi Arabia', 'SAU');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (193, 'St. Pierre and Miquelon', 'SPM');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (194, 'St. Kitts and Nevis', 'KNA');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (195, 'Seychelles', 'SYC');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (196, 'South Africa', 'ZAF');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (197, 'Senegal', 'SEN');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (198, 'St. Helena', 'SHN');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (199, 'Slovenia', 'SVN');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (200, 'Sierra Leone', 'SLE');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (201, 'San Marino', 'SMR');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (202, 'Singapore', 'SGP');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (203, 'Somalia', 'SOM');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (204, 'Spain', 'ESP');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (205, 'Serbia', 'SRB');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (206, 'St. Lucia', 'LCA');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (207, 'Sudan', 'SDN');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (208, 'Svalbard', 'SJM1');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (209, 'Sweden', 'SWE');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (210, 'South Georgia and the South Sandwich Is', 'SGS');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (211, 'Syria', 'SYR');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (212, 'Switzerland', 'CHE');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (213, 'United Arab Emirates', 'ARE');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (214, 'Trinidad and Tobago', 'TTO');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (215, 'Thailand', 'THA');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (216, 'Tajikistan', 'TJK');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (217, 'Turks and Caicos Islands', 'TCA');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (218, 'Tokelau', 'TKL');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (219, 'Tonga', 'TON');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (220, 'Togo', 'TGO');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (221, 'Sao Tome and Principe', 'STP');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (222, 'Tunisia', 'TUN');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (223, 'Turkey', 'TUR');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (224, 'Tuvalu', 'TUV');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (225, 'Taiwan', 'TWN');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (226, 'Turkmenistan', 'TKM');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (227, 'Tanzania, United Republic of', 'TZA');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (228, 'Uganda', 'UGA');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (229, 'United Kingdom', 'GBR');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (230, 'Ukraine', 'UKR');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (231, 'United States', 'USA');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (232, 'Burkina Faso', 'BFA');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (233, 'Uruguay', 'URY');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (234, 'Uzbekistan', 'UZB');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (235, 'St. Vincent and the Grenadines', 'VCT');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (236, 'Venezuela', 'VEN');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (237, 'British Virgin Islands', 'VGB');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (238, 'Vietnam', 'VNM');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (239, 'Virgin Islands', 'VIR');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (240, 'Namibia', 'NAM');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (241, 'West Bank', 'WE');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (242, 'Wallis and Futuna', 'WLF');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (243, 'Western Sahara', 'ESH');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (244, 'Wake Island', 'UMI6');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (245, 'Western Samoa', 'WSM');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (246, 'Swaziland', 'SWZ');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (247, 'Yemen', 'YEM');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (248, 'Zambia', 'ZMB');
INSERT INTO countries (country_id, country_name, abbreviation) VALUES (249, 'Zimbabwe', 'ZWE');