INSERT INTO geo.units (unit_id, unit_name, abbreviation, description) VALUES (1, 'Unknown', '??', NULL);
INSERT INTO geo.units (unit_id, unit_name, abbreviation, description) VALUES (2, 'square kilometers', 'sqkm', NULL);
INSERT INTO geo.units (unit_id, unit_name, abbreviation, description) VALUES (3, 'millimeters per year', 'mm/yr', NULL);
INSERT INTO geo.units (unit_id, unit_name, abbreviation, description) VALUES (4, 'number of days', '# days', NULL);
INSERT INTO geo.units (unit_id, unit_name, abbreviation, description) VALUES (5, 'millimeters per meter', 'mm/m', NULL);
INSERT INTO geo.units (unit_id, unit_name, abbreviation, description) VALUES (6, 'degrees celcius', 'C', NULL);
INSERT INTO geo.units (unit_id, unit_name, abbreviation, description) VALUES (7, 'grams per cubic centimeter', 'g/cm3', NULL);
INSERT INTO geo.units (unit_id, unit_name, abbreviation, description) VALUES (8, 'boolean', 'bool', NULL);
INSERT INTO geo.units (unit_id, unit_name, abbreviation, description) VALUES (9, 'percent', '%', NULL);
INSERT INTO geo.units (unit_id, unit_name, abbreviation, description) VALUES (10, 'decimal degrees', 'degrees', NULL);
INSERT INTO geo.units (unit_id, unit_name, abbreviation, description) VALUES (11, 'kilometers per square kilometer', 'km/km2', NULL);
INSERT INTO geo.units (unit_id, unit_name, abbreviation, description) VALUES (12, 'grams', 'g', NULL);
INSERT INTO geo.units (unit_id, unit_name, abbreviation, description) VALUES (13, 'kilograms', 'kg', NULL);
INSERT INTO geo.units (unit_id, unit_name, abbreviation, description) VALUES (14, 'meters', 'm', NULL);
INSERT INTO geo.units (unit_id, unit_name, abbreviation, description) VALUES (15, 'millimeters', 'mm', NULL);
INSERT INTO geo.units (unit_id, unit_name, abbreviation, description) VALUES (16, 'crossings/square km', 'xs/km2', NULL);
INSERT INTO geo.units (unit_id, unit_name, abbreviation, description) VALUES (17, 'dams/ square km', 'dams/km2', NULL);
INSERT INTO geo.units (unit_id, unit_name, abbreviation, description) VALUES (18, 'sites per square km', 'sites/km2', NULL);
INSERT INTO geo.units (unit_id, unit_name, abbreviation, description) VALUES (19, 'mines/square km', 'mines/sq km', NULL);