INSERT INTO states (state_id, country_id, state_name, abbreviation) VALUES (1, 231, 'Alabama', 'AL');
INSERT INTO states (state_id, country_id, state_name, abbreviation) VALUES (2, 231, 'Alaska', 'AK');
INSERT INTO states (state_id, country_id, state_name, abbreviation) VALUES (3, 231, 'Arkansas', 'AR');
INSERT INTO states (state_id, country_id, state_name, abbreviation) VALUES (4, 231, 'Arizona', 'AZ');
INSERT INTO states (state_id, country_id, state_name, abbreviation) VALUES (5, 231, 'California', 'CA');
INSERT INTO states (state_id, country_id, state_name, abbreviation) VALUES (6, 231, 'Colorado', 'CO');
INSERT INTO states (state_id, country_id, state_name, abbreviation) VALUES (7, 231, 'Connecticut', 'CT');
INSERT INTO states (state_id, country_id, state_name, abbreviation) VALUES (8, 231, 'District of Columbia', 'DC');
INSERT INTO states (state_id, country_id, state_name, abbreviation) VALUES (9, 231, 'Delaware', 'DE');
INSERT INTO states (state_id, country_id, state_name, abbreviation) VALUES (10, 231, 'Florida', 'FL');
INSERT INTO states (state_id, country_id, state_name, abbreviation) VALUES (11, 231, 'Georgia', 'GA');
INSERT INTO states (state_id, country_id, state_name, abbreviation) VALUES (12, 231, 'Hawaii', 'HI');
INSERT INTO states (state_id, country_id, state_name, abbreviation) VALUES (13, 231, 'Iowa', 'IA');
INSERT INTO states (state_id, country_id, state_name, abbreviation) VALUES (14, 231, 'Idaho', 'ID');
INSERT INTO states (state_id, country_id, state_name, abbreviation) VALUES (15, 231, 'Illinois', 'IL');
INSERT INTO states (state_id, country_id, state_name, abbreviation) VALUES (16, 231, 'Indiana', 'IN');
INSERT INTO states (state_id, country_id, state_name, abbreviation) VALUES (17, 231, 'Kansas', 'KS');
INSERT INTO states (state_id, country_id, state_name, abbreviation) VALUES (18, 231, 'Kentucky', 'KY');
INSERT INTO states (state_id, country_id, state_name, abbreviation) VALUES (19, 231, 'Louisiana', 'LA');
INSERT INTO states (state_id, country_id, state_name, abbreviation) VALUES (20, 231, 'Massachusetts', 'MA');
INSERT INTO states (state_id, country_id, state_name, abbreviation) VALUES (21, 231, 'Maryland', 'MD');
INSERT INTO states (state_id, country_id, state_name, abbreviation) VALUES (22, 231, 'Maine', 'ME');
INSERT INTO states (state_id, country_id, state_name, abbreviation) VALUES (23, 231, 'Michigan', 'MI');
INSERT INTO states (state_id, country_id, state_name, abbreviation) VALUES (24, 231, 'Minnesota', 'MN');
INSERT INTO states (state_id, country_id, state_name, abbreviation) VALUES (25, 231, 'Missouri', 'MO');
INSERT INTO states (state_id, country_id, state_name, abbreviation) VALUES (26, 231, 'Mississippi', 'MS');
INSERT INTO states (state_id, country_id, state_name, abbreviation) VALUES (27, 231, 'Montana', 'MT');
INSERT INTO states (state_id, country_id, state_name, abbreviation) VALUES (28, 231, 'North Carolina', 'NC');
INSERT INTO states (state_id, country_id, state_name, abbreviation) VALUES (29, 231, 'North Dakota', 'ND');
INSERT INTO states (state_id, country_id, state_name, abbreviation) VALUES (30, 231, 'Nebraska', 'NE');
INSERT INTO states (state_id, country_id, state_name, abbreviation) VALUES (31, 231, 'New Hampshire', 'NH');
INSERT INTO states (state_id, country_id, state_name, abbreviation) VALUES (32, 231, 'New Jersey', 'NJ');
INSERT INTO states (state_id, country_id, state_name, abbreviation) VALUES (33, 231, 'New Mexico', 'NM');
INSERT INTO states (state_id, country_id, state_name, abbreviation) VALUES (34, 231, 'Nevada', 'NV');
INSERT INTO states (state_id, country_id, state_name, abbreviation) VALUES (35, 231, 'New York', 'NY');
INSERT INTO states (state_id, country_id, state_name, abbreviation) VALUES (36, 231, 'Ohio', 'OH');
INSERT INTO states (state_id, country_id, state_name, abbreviation) VALUES (37, 231, 'Oklahoma', 'OK');
INSERT INTO states (state_id, country_id, state_name, abbreviation) VALUES (38, 231, 'Oregon', 'OR');
INSERT INTO states (state_id, country_id, state_name, abbreviation) VALUES (39, 231, 'Pennsylvania', 'PA');
INSERT INTO states (state_id, country_id, state_name, abbreviation) VALUES (40, 231, 'Rhode Island', 'RI');
INSERT INTO states (state_id, country_id, state_name, abbreviation) VALUES (41, 231, 'South Carolina', 'SC');
INSERT INTO states (state_id, country_id, state_name, abbreviation) VALUES (42, 231, 'South Dakota', 'SD');
INSERT INTO states (state_id, country_id, state_name, abbreviation) VALUES (43, 231, 'Tennessee', 'TN');
INSERT INTO states (state_id, country_id, state_name, abbreviation) VALUES (44, 231, 'Texas', 'TX');
INSERT INTO states (state_id, country_id, state_name, abbreviation) VALUES (45, 231, 'Utah', 'UT');
INSERT INTO states (state_id, country_id, state_name, abbreviation) VALUES (46, 231, 'Virginia', 'VA');
INSERT INTO states (state_id, country_id, state_name, abbreviation) VALUES (47, 231, 'Vermont', 'VT');
INSERT INTO states (state_id, country_id, state_name, abbreviation) VALUES (48, 231, 'Washington', 'WA');
INSERT INTO states (state_id, country_id, state_name, abbreviation) VALUES (49, 231, 'Wisconsin', 'WI');
INSERT INTO states (state_id, country_id, state_name, abbreviation) VALUES (50, 231, 'West Virginia', 'WV');
INSERT INTO states (state_id, country_id, state_name, abbreviation) VALUES (51, 231, 'Wyoming', 'WY');