INSERT INTO taxa_levels (taxa_level_id, taxa_level_name, taxa_level_rank) VALUES ( 1, 'Kingdom', 1);
INSERT INTO taxa_levels (taxa_level_id, taxa_level_name, taxa_level_rank) VALUES ( 2, 'Phylum', 2);
INSERT INTO taxa_levels (taxa_level_id, taxa_level_name, taxa_level_rank) VALUES ( 3, 'Class', 3);
INSERT INTO taxa_levels (taxa_level_id, taxa_level_name, taxa_level_rank) VALUES ( 4, 'SubClass', 4);
INSERT INTO taxa_levels (taxa_level_id, taxa_level_name, taxa_level_rank) VALUES ( 5, 'Order', 5);
INSERT INTO taxa_levels (taxa_level_id, taxa_level_name, taxa_level_rank) VALUES ( 6, 'SubOrder', 6);
INSERT INTO taxa_levels (taxa_level_id, taxa_level_name, taxa_level_rank) VALUES ( 7, 'Family', 7);
INSERT INTO taxa_levels (taxa_level_id, taxa_level_name, taxa_level_rank) VALUES ( 8, 'SubFamily', 8);
INSERT INTO taxa_levels (taxa_level_id, taxa_level_name, taxa_level_rank) VALUES ( 9, 'Tribe', 9);
INSERT INTO taxa_levels (taxa_level_id, taxa_level_name, taxa_level_rank) VALUES (10, 'Genus', 10);
INSERT INTO taxa_levels (taxa_level_id, taxa_level_name, taxa_level_rank) VALUES (11, 'Species', 11);
INSERT INTO taxa_levels (taxa_level_id, taxa_level_name, taxa_level_rank) VALUES (12, 'SubSpecies', 12);
