INSERT INTO sample.sample_methods (sample_method_id, sample_method_name, is_active) VALUES (1  , 'Aerial net', True);
INSERT INTO sample.sample_methods (sample_method_id, sample_method_name, is_active) VALUES (2  , 'Black light', True);
INSERT INTO sample.sample_methods (sample_method_id, sample_method_name, is_active) VALUES (3  , 'Corer', True);
INSERT INTO sample.sample_methods (sample_method_id, sample_method_name, is_active) VALUES (4  , 'Dip net', True);
INSERT INTO sample.sample_methods (sample_method_id, sample_method_name, is_active) VALUES (5  , 'Dissected gut', True);
INSERT INTO sample.sample_methods (sample_method_id, sample_method_name, is_active) VALUES (6  , 'Dissection', True);
INSERT INTO sample.sample_methods (sample_method_id, sample_method_name, is_active) VALUES (7  , 'Drift net', True);
INSERT INTO sample.sample_methods (sample_method_id, sample_method_name, is_active) VALUES (8  , 'Ekman grab', True);
INSERT INTO sample.sample_methods (sample_method_id, sample_method_name, is_active) VALUES (9  , 'Electrofisher', True);
INSERT INTO sample.sample_methods (sample_method_id, sample_method_name, is_active) VALUES (10 , 'Emergence trap', True);
INSERT INTO sample.sample_methods (sample_method_id, sample_method_name, is_active) VALUES (11 , 'Funnel trap', True);
INSERT INTO sample.sample_methods (sample_method_id, sample_method_name, is_active) VALUES (12 , 'Grab', True);
INSERT INTO sample.sample_methods (sample_method_id, sample_method_name, is_active) VALUES (13 , 'Hess net', True);
INSERT INTO sample.sample_methods (sample_method_id, sample_method_name, is_active) VALUES (14 , 'Hester dendy', True);
INSERT INTO sample.sample_methods (sample_method_id, sample_method_name, is_active) VALUES (15 , 'K-B corer', True);
INSERT INTO sample.sample_methods (sample_method_id, sample_method_name, is_active) VALUES (16 , 'Kick net', True);
INSERT INTO sample.sample_methods (sample_method_id, sample_method_name, is_active) VALUES (17 , 'Minnow trap', True);
INSERT INTO sample.sample_methods (sample_method_id, sample_method_name, is_active) VALUES (18 , 'NAWQA-Depositional', True);
INSERT INTO sample.sample_methods (sample_method_id, sample_method_name, is_active) VALUES (19 , 'Other Artificial', True);
INSERT INTO sample.sample_methods (sample_method_id, sample_method_name, is_active) VALUES (20 , 'Other Qualitative', True);
INSERT INTO sample.sample_methods (sample_method_id, sample_method_name, is_active) VALUES (21 , 'Plankton net', True);
INSERT INTO sample.sample_methods (sample_method_id, sample_method_name, is_active) VALUES (22 , 'Ponar grab', True);
INSERT INTO sample.sample_methods (sample_method_id, sample_method_name, is_active) VALUES (23 , 'Report', True);
INSERT INTO sample.sample_methods (sample_method_id, sample_method_name, is_active) VALUES (24 , 'Slack sampler', True);
INSERT INTO sample.sample_methods (sample_method_id, sample_method_name, is_active) VALUES (25 , 'Stomach pump', True);
INSERT INTO sample.sample_methods (sample_method_id, sample_method_name, is_active) VALUES (26 , 'Surber net', True);
INSERT INTO sample.sample_methods (sample_method_id, sample_method_name, is_active) VALUES (27 , 'Tee', True);
INSERT INTO sample.sample_methods (sample_method_id, sample_method_name, is_active) VALUES (28 , 'Unspecified', True);
INSERT INTO sample.sample_methods (sample_method_id, sample_method_name, is_active) VALUES (29, 'Leaf Decomposition Bags', False);