INSERT INTO geo.systems (system_id, system_name, ecosystem_id, is_active) VALUES (1, 'Lake', 3, TRUE);
INSERT INTO geo.systems (system_id, system_name, ecosystem_id, is_active) VALUES (2, 'Pond', 3, TRUE);
INSERT INTO geo.systems (system_id, system_name, ecosystem_id, is_active) VALUES (3, 'Regulated River', 2, TRUE);
INSERT INTO geo.systems (system_id, system_name, ecosystem_id, is_active) VALUES (4, 'Reservoir', 3, TRUE);
INSERT INTO geo.systems (system_id, system_name, ecosystem_id, is_active) VALUES (5, 'Spring (flowing)', 2, TRUE);
INSERT INTO geo.systems (system_id, system_name, ecosystem_id, is_active) VALUES (6, 'Spring (static)', 3, TRUE);
INSERT INTO geo.systems (system_id, system_name, ecosystem_id, is_active) VALUES (7, 'Stream', 2, TRUE);
INSERT INTO geo.systems (system_id, system_name, ecosystem_id, is_active) VALUES (8, 'Wetland', 3, TRUE);
INSERT INTO geo.systems (system_id, system_name, ecosystem_id, is_active) VALUES (9, 'Spring', 2, FALSE);
INSERT INTO geo.systems (system_id, system_name, ecosystem_id, is_active) VALUES (10, 'Lagoon', 2, FALSE);
INSERT INTO geo.systems (system_id, system_name, ecosystem_id, is_active) VALUES (11, 'Seep', 2, FALSE);
INSERT INTO geo.systems (system_id, system_name, ecosystem_id, is_active) VALUES (12, 'Groundwater', 2, FALSE);
INSERT INTO geo.systems (system_id, system_name, ecosystem_id, is_active) VALUES (13, 'Artifical', 2, FALSE);