INSERT INTO Geo.Habitats (HabitatID, HabitatName, EcosystemID, IsActive) VALUES (1, 'Aerial', 3, TRUE);
INSERT INTO Geo.Habitats (HabitatID, HabitatName, EcosystemID, IsActive) VALUES (2, 'Benthos', 3, TRUE);
INSERT INTO Geo.Habitats (HabitatID, HabitatName, EcosystemID, IsActive) VALUES (3, 'Littoral', 3, TRUE);
INSERT INTO Geo.Habitats (HabitatID, HabitatName, EcosystemID, IsActive) VALUES (4, 'Multiple', 1, FALSE);
INSERT INTO Geo.Habitats (HabitatID, HabitatName, EcosystemID, IsActive) VALUES (5, 'Other', 1, TRUE);
INSERT INTO Geo.Habitats (HabitatID, HabitatName, EcosystemID, IsActive) VALUES (6, 'Pelagic', 3, TRUE);
INSERT INTO Geo.Habitats (HabitatID, HabitatName, EcosystemID, IsActive) VALUES (7, 'Pelagic/Water Column', 3, TRUE);
INSERT INTO Geo.Habitats (HabitatID, HabitatName, EcosystemID, IsActive) VALUES (8, 'Pool', 2, TRUE);
INSERT INTO Geo.Habitats (HabitatID, HabitatName, EcosystemID, IsActive) VALUES (9, 'Reachwide', 2, TRUE);
INSERT INTO Geo.Habitats (HabitatID, HabitatName, EcosystemID, IsActive) VALUES (10, 'Stomach', 1, TRUE);
INSERT INTO Geo.Habitats (HabitatID, HabitatName, EcosystemID, IsActive) VALUES (11, 'Targeted Riffle', 2, TRUE);
INSERT INTO Geo.Habitats (HabitatID, HabitatName, EcosystemID, IsActive) VALUES (12, 'Unspecified', 1, FALSE);