INSERT INTO Geo.Systems (SystemID, SystemName, EcosystemID, IsActive) VALUES (1, 'Lake', 3, TRUE);
INSERT INTO Geo.Systems (SystemID, SystemName, EcosystemID, IsActive) VALUES (2, 'Pond', 3, TRUE);
INSERT INTO Geo.Systems (SystemID, SystemName, EcosystemID, IsActive) VALUES (3, 'Regulated River', 2, TRUE);
INSERT INTO Geo.Systems (SystemID, SystemName, EcosystemID, IsActive) VALUES (4, 'Reservoir', 3, TRUE);
INSERT INTO Geo.Systems (SystemID, SystemName, EcosystemID, IsActive) VALUES (5, 'Spring (flowing)', 2, TRUE);
INSERT INTO Geo.Systems (SystemID, SystemName, EcosystemID, IsActive) VALUES (6, 'Spring (static)', 3, TRUE);
INSERT INTO Geo.Systems (SystemID, SystemName, EcosystemID, IsActive) VALUES (7, 'Stream', 2, TRUE);
INSERT INTO Geo.Systems (SystemID, SystemName, EcosystemID, IsActive) VALUES (8, 'Wetland', 3, TRUE);
INSERT INTO Geo.Systems (SystemID, SystemName, EcosystemID, IsActive) VALUES (9, 'Spring', 2, FALSE);
INSERT INTO Geo.Systems (SystemID, SystemName, EcosystemID, IsActive) VALUES (10, 'Lagoon', 2, FALSE);
INSERT INTO Geo.Systems (SystemID, SystemName, EcosystemID, IsActive) VALUES (11, 'Seep', 2, FALSE);
INSERT INTO Geo.Systems (SystemID, SystemName, EcosystemID, IsActive) VALUES (12, 'Groundwater', 2, FALSE);
INSERT INTO Geo.Systems (SystemID, SystemName, EcosystemID, IsActive) VALUES (13, 'Artifical', 2, FALSE);