INSERT INTO sample.projects(project_id, project_name, description, is_private) VALUES(1, 'YNP-TREY', 'None', False);
INSERT INTO sample.projects(project_id, project_name, description, is_private) VALUES(2, 'R6-USU-WEST', 'None', False);
INSERT INTO sample.projects(project_id, project_name, description, is_private) VALUES(3, 'PIBO', 'None', False);
INSERT INTO sample.projects(project_id, project_name, description, is_private) VALUES(4, 'USU-STAR-I', 'None', False);
INSERT INTO sample.projects(project_id, project_name, description, is_private) VALUES(6, 'CA-R5', 'None', False);
INSERT INTO sample.projects(project_id, project_name, description, is_private) VALUES(7, 'R6-USU-EAST', 'None', False);
INSERT INTO sample.projects(project_id, project_name, description, is_private) VALUES(8, 'OR-DEQ', 'None', False);
INSERT INTO sample.projects(project_id, project_name, description, is_private) VALUES(9, 'WA-DOE', 'None', False);
INSERT INTO sample.projects(project_id, project_name, description, is_private) VALUES(10, 'EMAP-WEST', 'None', False);
INSERT INTO sample.projects(project_id, project_name, description, is_private) VALUES(11, 'WSA-EAST', 'None', False);
INSERT INTO sample.projects(project_id, project_name, description, is_private) VALUES(12, 'USU-STAR-II', 'None', False);
INSERT INTO sample.projects(project_id, project_name, description, is_private) VALUES(14, 'CO-REMAP', 'Colorado REMAP', False);
INSERT INTO sample.projects(project_id, project_name, description, is_private) VALUES(15, 'CO-NAQWA', 'Colorado NAQWA', False);
INSERT INTO sample.projects(project_id, project_name, description, is_private) VALUES(16, 'CO-DPHE', 'Colorado DHPE', False);
INSERT INTO sample.projects(project_id, project_name, description, is_private) VALUES(17, 'NAMC', 'NAMC - internal project samples', False);
INSERT INTO sample.projects(project_id, project_name, description, is_private) VALUES(18, 'NAQWA-REF', 'None', False);
INSERT INTO sample.projects(project_id, project_name, description, is_private) VALUES(19, 'AREMP', 'None', False);
INSERT INTO sample.projects(project_id, project_name, description, is_private) VALUES(20, 'USU-DNA', 'None', False);
INSERT INTO sample.projects(project_id, project_name, description, is_private) VALUES(21, 'UT-DEQ', 'Utah - Department of Environmental Quality', False);
INSERT INTO sample.projects(project_id, project_name, description, is_private) VALUES(22, 'HAWKINS-WAKELEY', 'Ellen Wakeley MS', False);
INSERT INTO sample.projects(project_id, project_name, description, is_private) VALUES(23, 'FGD_DblPeak', 'Double Peak Buglab/WAPA', False);
INSERT INTO sample.projects(project_id, project_name, description, is_private) VALUES(24, 'Rotenone', 'Buglab Rotenone/BrownTrout', False);
INSERT INTO sample.projects(project_id, project_name, description, is_private) VALUES(25, 'RBFWO', 'BLM/USFWS Gravel augmentation effectiveness monitoring', False);
INSERT INTO sample.projects(project_id, project_name, description, is_private) VALUES(26, 'NV-DEP', 'Nevada - Devision of Environmental Protection', False);
INSERT INTO sample.projects(project_id, project_name, description, is_private) VALUES(27, 'LoganRiver-LongTerm', 'None', False);
INSERT INTO sample.projects(project_id, project_name, description, is_private) VALUES(28, 'HAWKINS-CWE', 'None', False);
INSERT INTO sample.projects(project_id, project_name, description, is_private) VALUES(29, 'EMAP-NE-Lakes', 'None', False);
INSERT INTO sample.projects(project_id, project_name, description, is_private) VALUES(30, 'BuglabProblems', 'Buglab samples with problematic taxonomy or siteInfo that should be excluded from MapIT, the query tool, and other analytical uses.', False);
INSERT INTO sample.projects(project_id, project_name, description, is_private) VALUES(31, 'BuglabQAQC', 'Buglab Taxonomy and OTU QAQC', False);
INSERT INTO sample.projects(project_id, project_name, description, is_private) VALUES(32, 'FGD_SemiAnnual', 'Green River SemiAnnual Fish sampling, with accompanying drift', False);
INSERT INTO sample.projects(project_id, project_name, description, is_private) VALUES(33, 'FGD_LT', 'Green River Long Term (quarterly samples)', False);
INSERT INTO sample.projects(project_id, project_name, description, is_private) VALUES(34, 'FGD_Misc', 'Other Green River', False);
INSERT INTO sample.projects(project_id, project_name, description, is_private) VALUES(35, 'Kansas', 'Kansas Data (Hawkins / Vander Laan)', False);
INSERT INTO sample.projects(project_id, project_name, description, is_private) VALUES(36, 'NPS', 'National Park Services (Private Collective)', False);
INSERT INTO sample.projects(project_id, project_name, description, is_private) VALUES(37, 'UT-CO-Mollusks', 'Hawkins Mollusk Data', False);
INSERT INTO sample.projects(project_id, project_name, description, is_private) VALUES(38, 'AIM-WRSA', 'WestWide AIM 2013-2015', False);
INSERT INTO sample.projects(project_id, project_name, description, is_private) VALUES(39, 'NorCal', 'Nicoles masters project', True);
INSERT INTO sample.projects(project_id, project_name, description, is_private) VALUES(40, 'GSENM', 'GrandStaircase national monument', False);
INSERT INTO sample.projects(project_id, project_name, description, is_private) VALUES(41, 'AIM-COPLT', 'Colorado plateau AIM', False);
INSERT INTO sample.projects(project_id, project_name, description, is_private) VALUES(42, 'AIM-NV', 'NV AIM', False);
INSERT INTO sample.projects(project_id, project_name, description, is_private) VALUES(43, 'AIM-UT', 'UT AIM pilot', False);
INSERT INTO sample.projects(project_id, project_name, description, is_private) VALUES(44, 'WY-Study', 'Wyoming alkalinity prediction study', False);
INSERT INTO sample.projects(project_id, project_name, description, is_private) VALUES(45, 'EcoAnalysts', 'EcoAnalyst metric computation data', False);
INSERT INTO sample.projects(project_id, project_name, description, is_private) VALUES(46, 'USFS', 'USFS', False);
INSERT INTO sample.projects(project_id, project_name, description, is_private) VALUES(47, 'USU', 'Utah State University - Other', False);
INSERT INTO sample.projects(project_id, project_name, description, is_private) VALUES(48, 'NAMC-general', 'NAMC - general samples', False);
INSERT INTO sample.projects(project_id, project_name, description, is_private) VALUES(49, 'AIM', 'AIM 2017-present', False);
INSERT INTO sample.projects(project_id, project_name, description, is_private) VALUES(50, 'BLM', 'BLM - general samples', False);
INSERT INTO sample.projects(project_id, project_name, description, is_private) VALUES(51, 'GSL', 'Great Salt Lake research project; a collaborative effort between Wayne Wurtsbaugh and Trip Armstrong', False);
INSERT INTO sample.projects(project_id, project_name, description, is_private) VALUES(52, 'AK-Model', 'New Alaska Model Data (2019)', False);
