INSERT INTO sample.projects(project_id, project_name, project_type_id, description, is_private) VALUES(1, 'YNP-TREY', 1, 'None', False);
INSERT INTO sample.projects(project_id, project_name, project_type_id, description, is_private) VALUES(2, 'R6-USU-WEST', 1, 'None', False);
INSERT INTO sample.projects(project_id, project_name, project_type_id, description, is_private) VALUES(3, 'PIBO', 1, 'None', False);
INSERT INTO sample.projects(project_id, project_name, project_type_id, description, is_private) VALUES(4, 'USU-STAR-I', 1, 'None', False);
INSERT INTO sample.projects(project_id, project_name, project_type_id, description, is_private) VALUES(6, 'CA-R5', 1, 'None', False);
INSERT INTO sample.projects(project_id, project_name, project_type_id, description, is_private) VALUES(7, 'R6-USU-EAST', 1, 'None', False);
INSERT INTO sample.projects(project_id, project_name, project_type_id, description, is_private) VALUES(8, 'OR-DEQ', 1, 'None', False);
INSERT INTO sample.projects(project_id, project_name, project_type_id, description, is_private) VALUES(9, 'WA-DOE', 1, 'None', False);
INSERT INTO sample.projects(project_id, project_name, project_type_id, description, is_private) VALUES(10, 'EMAP-WEST', 1, 'None', False);
INSERT INTO sample.projects(project_id, project_name, project_type_id, description, is_private) VALUES(11, 'WSA-EAST', 1, 'None', False);
INSERT INTO sample.projects(project_id, project_name, project_type_id, description, is_private) VALUES(12, 'USU-STAR-II', 1, 'None', False);
INSERT INTO sample.projects(project_id, project_name, project_type_id, description, is_private) VALUES(14, 'CO-REMAP', 1, 'Colorado REMAP', False);
INSERT INTO sample.projects(project_id, project_name, project_type_id, description, is_private) VALUES(15, 'CO-NAQWA', 1, 'Colorado NAQWA', False);
INSERT INTO sample.projects(project_id, project_name, project_type_id, description, is_private) VALUES(16, 'CO-DPHE', 1, 'Colorado DHPE', False);
INSERT INTO sample.projects(project_id, project_name, project_type_id, description, is_private) VALUES(17, 'NAMC', 1, 'NAMC - internal project samples', False);
INSERT INTO sample.projects(project_id, project_name, project_type_id, description, is_private) VALUES(18, 'NAQWA-REF', 1, 'None', False);
INSERT INTO sample.projects(project_id, project_name, project_type_id, description, is_private) VALUES(19, 'AREMP', 1, 'None', False);
INSERT INTO sample.projects(project_id, project_name, project_type_id, description, is_private) VALUES(20, 'USU-DNA', 1, 'None', False);
INSERT INTO sample.projects(project_id, project_name, project_type_id, description, is_private) VALUES(21, 'UT-DEQ', 1, 'Utah - Department of Environmental Quality', False);
INSERT INTO sample.projects(project_id, project_name, project_type_id, description, is_private) VALUES(22, 'HAWKINS-WAKELEY', 1, 'Ellen Wakeley MS', False);
INSERT INTO sample.projects(project_id, project_name, project_type_id, description, is_private) VALUES(23, 'FGD_DblPeak', 1, 'Double Peak Buglab/WAPA', False);
INSERT INTO sample.projects(project_id, project_name, project_type_id, description, is_private) VALUES(24, 'Rotenone', 1, 'Buglab Rotenone/BrownTrout', False);
INSERT INTO sample.projects(project_id, project_name, project_type_id, description, is_private) VALUES(25, 'RBFWO', 1, 'BLM/USFWS Gravel augmentation effectiveness monitoring', False);
INSERT INTO sample.projects(project_id, project_name, project_type_id, description, is_private) VALUES(26, 'NV-DEP', 1, 'Nevada - Devision of Environmental Protection', False);
INSERT INTO sample.projects(project_id, project_name, project_type_id, description, is_private) VALUES(27, 'LoganRiver-LongTerm', 1, 'None', False);
INSERT INTO sample.projects(project_id, project_name, project_type_id, description, is_private) VALUES(28, 'HAWKINS-CWE', 1, 'None', False);
INSERT INTO sample.projects(project_id, project_name, project_type_id, description, is_private) VALUES(29, 'EMAP-NE-Lakes', 1, 'None', False);
INSERT INTO sample.projects(project_id, project_name, project_type_id, description, is_private) VALUES(30, 'BuglabProblems', 1, 'Buglab samples with problematic taxonomy or siteInfo that should be excluded from MapIT, the query tool, and other analytical uses.', False);
INSERT INTO sample.projects(project_id, project_name, project_type_id, description, is_private) VALUES(31, 'BuglabQAQC', 1, 'Buglab Taxonomy and OTU QAQC', False);
INSERT INTO sample.projects(project_id, project_name, project_type_id, description, is_private) VALUES(32, 'FGD_SemiAnnual', 1, 'Green River SemiAnnual Fish sampling, with accompanying drift', False);
INSERT INTO sample.projects(project_id, project_name, project_type_id, description, is_private) VALUES(33, 'FGD_LT', 1, 'Green River Long Term (quarterly samples)', False);
INSERT INTO sample.projects(project_id, project_name, project_type_id, description, is_private) VALUES(34, 'FGD_Misc', 1, 'Other Green River', False);
INSERT INTO sample.projects(project_id, project_name, project_type_id, description, is_private) VALUES(35, 'Kansas', 1, 'Kansas Data (Hawkins / Vander Laan)', False);
INSERT INTO sample.projects(project_id, project_name, project_type_id, description, is_private) VALUES(36, 'NPS', 1, 'National Park Services (Private Collective)', False);
INSERT INTO sample.projects(project_id, project_name, project_type_id, description, is_private) VALUES(37, 'UT-CO-Mollusks', 1, 'Hawkins Mollusk Data', False);
INSERT INTO sample.projects(project_id, project_name, project_type_id, description, is_private) VALUES(38, 'AIM-WRSA', 1, 'WestWide AIM 2013-2015', False);
INSERT INTO sample.projects(project_id, project_name, project_type_id, description, is_private) VALUES(39, 'NorCal', 1, 'Nicoles masters project', True);
INSERT INTO sample.projects(project_id, project_name, project_type_id, description, is_private) VALUES(40, 'GSENM', 1, 'GrandStaircase national monument', False);
INSERT INTO sample.projects(project_id, project_name, project_type_id, description, is_private) VALUES(41, 'AIM-COPLT', 1, 'Colorado plateau AIM', False);
INSERT INTO sample.projects(project_id, project_name, project_type_id, description, is_private) VALUES(42, 'AIM-NV', 1, 'NV AIM', False);
INSERT INTO sample.projects(project_id, project_name, project_type_id, description, is_private) VALUES(43, 'AIM-UT', 1, 'UT AIM pilot', False);
INSERT INTO sample.projects(project_id, project_name, project_type_id, description, is_private) VALUES(44, 'WY-Study', 1, 'Wyoming alkalinity prediction study', False);
INSERT INTO sample.projects(project_id, project_name, project_type_id, description, is_private) VALUES(45, 'EcoAnalysts', 1, 'EcoAnalyst metric computation data', False);
INSERT INTO sample.projects(project_id, project_name, project_type_id, description, is_private) VALUES(46, 'USFS', 1, 'USFS', False);
INSERT INTO sample.projects(project_id, project_name, project_type_id, description, is_private) VALUES(47, 'USU', 1, 'Utah State University - Other', False);
INSERT INTO sample.projects(project_id, project_name, project_type_id, description, is_private) VALUES(48, 'NAMC-general', 1, 'NAMC - general samples', False);
INSERT INTO sample.projects(project_id, project_name, project_type_id, description, is_private) VALUES(49, 'AIM', 1, 'AIM 2017-present', False);
INSERT INTO sample.projects(project_id, project_name, project_type_id, description, is_private) VALUES(50, 'BLM', 1, 'BLM - general samples', False);
INSERT INTO sample.projects(project_id, project_name, project_type_id, description, is_private) VALUES(51, 'GSL', 1, 'Great Salt Lake research project; a collaborative effort between Wayne Wurtsbaugh and Trip Armstrong', False);
INSERT INTO sample.projects(project_id, project_name, project_type_id, description, is_private) VALUES(52, 'AK-Model', 1, 'New Alaska Model Data (2019)', False);
