INSERT INTO sample.projects (project_id,project_name,description,project_type_id,is_private) VALUES (1,'YNP-TREY',NULL,1,False);
INSERT INTO sample.projects (project_id,project_name,description,project_type_id,is_private) VALUES (2,'R6-USU-WEST',NULL,1,False);
INSERT INTO sample.projects (project_id,project_name,description,project_type_id,is_private) VALUES (3,'PIBO',NULL,1,False);
INSERT INTO sample.projects (project_id,project_name,description,project_type_id,is_private) VALUES (4,'USU-STAR-I',NULL,1,False);
INSERT INTO sample.projects (project_id,project_name,description,project_type_id,is_private) VALUES (6,'CA-R5',NULL,1,False);
INSERT INTO sample.projects (project_id,project_name,description,project_type_id,is_private) VALUES (7,'R6-USU-EAST',NULL,1,False);
INSERT INTO sample.projects (project_id,project_name,description,project_type_id,is_private) VALUES (8,'OR-DEQ',NULL,1,False);
INSERT INTO sample.projects (project_id,project_name,description,project_type_id,is_private) VALUES (9,'WA-DOE',NULL,1,False);
INSERT INTO sample.projects (project_id,project_name,description,project_type_id,is_private) VALUES (10,'EMAP-WEST',NULL,1,False);
INSERT INTO sample.projects (project_id,project_name,description,project_type_id,is_private) VALUES (11,'WSA-EAST',NULL,1,False);
INSERT INTO sample.projects (project_id,project_name,description,project_type_id,is_private) VALUES (12,'USU-STAR-II',NULL,1,False);
INSERT INTO sample.projects (project_id,project_name,description,project_type_id,is_private) VALUES (14,'CO-REMAP','Colorado REMAP',1,False);
INSERT INTO sample.projects (project_id,project_name,description,project_type_id,is_private) VALUES (15,'CO-NAQWA','Colorado NAQWA',1,False);
INSERT INTO sample.projects (project_id,project_name,description,project_type_id,is_private) VALUES (16,'CO-DPHE','Colorado DHPE',1,False);
INSERT INTO sample.projects (project_id,project_name,description,project_type_id,is_private) VALUES (17,'NAMC','NAMC - internal project samples',1,False);
INSERT INTO sample.projects (project_id,project_name,description,project_type_id,is_private) VALUES (18,'NAQWA-REF',NULL,1,False);
INSERT INTO sample.projects (project_id,project_name,description,project_type_id,is_private) VALUES (19,'AREMP',NULL,1,False);
INSERT INTO sample.projects (project_id,project_name,description,project_type_id,is_private) VALUES (20,'USU-DNA',NULL,1,False);
INSERT INTO sample.projects (project_id,project_name,description,project_type_id,is_private) VALUES (21,'UT-DEQ','Utah - Department of Environmental Quality',1,False);
INSERT INTO sample.projects (project_id,project_name,description,project_type_id,is_private) VALUES (22,'HAWKINS-WAKELEY','Ellen Wakeley MS',1,False);
INSERT INTO sample.projects (project_id,project_name,description,project_type_id,is_private) VALUES (23,'FGD_DblPeak','Double Peak Buglab/WAPA',1,False);
INSERT INTO sample.projects (project_id,project_name,description,project_type_id,is_private) VALUES (24,'Rotenone','Buglab Rotenone/BrownTrout',1,False);
INSERT INTO sample.projects (project_id,project_name,description,project_type_id,is_private) VALUES (25,'RBFWO','BLM/USFWS Gravel augmentation effectiveness monitoring',1,False);
INSERT INTO sample.projects (project_id,project_name,description,project_type_id,is_private) VALUES (26,'NV-DEP','Nevada - Devision of Environmental Protection',1,False);
INSERT INTO sample.projects (project_id,project_name,description,project_type_id,is_private) VALUES (27,'LoganRiver-LongTerm',NULL,1,False);
INSERT INTO sample.projects (project_id,project_name,description,project_type_id,is_private) VALUES (28,'HAWKINS-CWE',NULL,1,False);
INSERT INTO sample.projects (project_id,project_name,description,project_type_id,is_private) VALUES (29,'EMAP-NE-Lakes',NULL,1,False);
INSERT INTO sample.projects (project_id,project_name,description,project_type_id,is_private) VALUES (30,'BuglabProblems','Buglab samples with problematic taxonomy or siteInfo that should be excluded from MapIT, the query tool, and other analytical uses.',1,False);
INSERT INTO sample.projects (project_id,project_name,description,project_type_id,is_private) VALUES (31,'BuglabQAQC','Buglab Taxonomy and OTU QAQC',1,False);
INSERT INTO sample.projects (project_id,project_name,description,project_type_id,is_private) VALUES (32,'FGD_SemiAnnual','Green River SemiAnnual Fish sampling, with accompanying drift',1,False);
INSERT INTO sample.projects (project_id,project_name,description,project_type_id,is_private) VALUES (33,'FGD_LT','Green River Long Term (quarterly samples)',1,False);
INSERT INTO sample.projects (project_id,project_name,description,project_type_id,is_private) VALUES (34,'FGD_Misc','Other Green River',1,False);
INSERT INTO sample.projects (project_id,project_name,description,project_type_id,is_private) VALUES (35,'Kansas','Kansas Data (Hawkins / Vander Laan)',1,False);
INSERT INTO sample.projects (project_id,project_name,description,project_type_id,is_private) VALUES (36,'NPS','National Park Services (Private Collective)',1,False);
INSERT INTO sample.projects (project_id,project_name,description,project_type_id,is_private) VALUES (37,'UT-CO-Mollusks','Hawkins Mollusk Data',1,False);
INSERT INTO sample.projects (project_id,project_name,description,project_type_id,is_private) VALUES (38,'AIM-WRSA','WestWide AIM 2013-2015',1,False);
INSERT INTO sample.projects (project_id,project_name,description,project_type_id,is_private) VALUES (39,'NorCal','Nicoles masters project',1,True);
INSERT INTO sample.projects (project_id,project_name,description,project_type_id,is_private) VALUES (40,'GSENM','GrandStaircase national monument',1,False);
INSERT INTO sample.projects (project_id,project_name,description,project_type_id,is_private) VALUES (41,'AIM-COPLT','Colorado plateau AIM',1,False);
INSERT INTO sample.projects (project_id,project_name,description,project_type_id,is_private) VALUES (42,'AIM-NV','NV AIM',1,False);
INSERT INTO sample.projects (project_id,project_name,description,project_type_id,is_private) VALUES (43,'AIM-UT','UT AIM pilot',1,False);
INSERT INTO sample.projects (project_id,project_name,description,project_type_id,is_private) VALUES (44,'WY-Study','Wyoming alkalinity prediction study',1,False);
INSERT INTO sample.projects (project_id,project_name,description,project_type_id,is_private) VALUES (45,'EcoAnalysts','EcoAnalyst metric computation data',1,False);
INSERT INTO sample.projects (project_id,project_name,description,project_type_id,is_private) VALUES (46,'USFS','USFS',1,False);
INSERT INTO sample.projects (project_id,project_name,description,project_type_id,is_private) VALUES (47,'USU','Utah State University - Other',1,False);
INSERT INTO sample.projects (project_id,project_name,description,project_type_id,is_private) VALUES (48,'NAMC-general','NAMC - general samples',1,False);
INSERT INTO sample.projects (project_id,project_name,description,project_type_id,is_private) VALUES (49,'AIM','AIM 2017-present',1,False);
INSERT INTO sample.projects (project_id,project_name,description,project_type_id,is_private) VALUES (50,'BLM','BLM - general samples',1,False);
INSERT INTO sample.projects (project_id,project_name,description,project_type_id,is_private) VALUES (51,'GSL','Great Salt Lake research project; a collaborative effort between Wayne Wurtsbaugh and Trip Armstrong',1,False);
INSERT INTO sample.projects (project_id,project_name,description,project_type_id,is_private) VALUES (52,'AK-Model','New Alaska Model Data (2019)',1,False);
INSERT INTO sample.projects (project_id,project_name,description,project_type_id,is_private) VALUES (53,'Mineral','USFS Mineral creek study',1,False);
INSERT INTO sample.projects (project_id,project_name,description,project_type_id,is_private) VALUES (54,'ZION-Drift','ZIon National Park Drift Samples',1,False);
